config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  devise_for :users
  root to: 'home#index'

  resources :rates, except: %i(new show edit update)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency.rb
class Currency < ApplicationRecord
  has_many :rates_from, class_name: 'Rate', foreign_key: 'currency_from_id'
  has_many :rates_to, class_name: 'Rate', foreign_key: 'currency_to_id'
  validates :contraction, presence: true
  validates :description, presence: true

  def rates
    Rate.where('currency_from_id = ? OR currency_to_id = ?', id, id )
  end
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :user
  belongs_to :currency_from, class_name: 'Currency'
  belongs_to :currency_to, class_name: 'Currency'

end

app/models/user.rb
class User < ApplicationRecord
  has_many :rates
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CurrencyApiError do |error|
    flash[:alert] = error.message
    redirect_back(fallback_location: root_path)
  end

  private

  def after_sign_in_path_for(resource)
    rates_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  before_action :authenticate_user!

  def index
   @rates = Rate.where(user: current_user).includes(:currency_from, :currency_to)
  end

  def create
    @rate = RateCreator.call(rate_params)
    if @rate.save
      flash[:notice] = 'Exchange rates successfully added'
      redirect_to rates_path
    else
      flash[:alert] = @rate.errors.messages
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @rate = Rate.find(params[:id])
    if @rate.destroy
      flash[:notice] = 'Exchange rates successfully deleted'
      redirect_to rates_path
    else
      flash[:alert] = @rate.errors.messages
      redirect_to rates_path
    end
  end

  private

  def rate_params
    merge_params = { user: current_user }
    params.require(:rate).permit(:currency_from_id, :currency_to_id).merge!(merge_params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="wrapper-home">
  <div class="container">
    <p class="title tip">Login and save your own currency rates</p>
    <p class="title">Popular Exchange Rates</p>
    <table class="table">
      <thead>
      <tr>
        <th class="text-left">Currency From</th>
        <th class="text-left">Currency To</th>
        <th class="text-left">Amount</th>
      </tr>
      </thead>
      <!--Static data for avoid API requests
      (only 10 requests per month for free account)-->
      <tbody>
        <tr>
          <td class="text-left">
            United States Dolar
          </td>
          <td class="text-left">
            Ukrainian Hryvnia
          </td>
          <td class="text-left">
            27.8
          </td>
        </tr>
        <tr>
          <td class="text-left">
            Euro
          </td>
          <td class="text-left">
            Ukrainian Hryvnia
          </td>
          <td class="text-left">
            31.65
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoaxsoftTestProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <% if flash[:alert].present? %>
    <%= javascript_tag do %>
        toastr.error("<%= flash[:alert] %>")
    <% end %>
  <% end %>
  <% if flash[:notice].present? %>
    <%= javascript_tag do %>
      toastr.info("<%= flash[:notice] %>")
    <% end %>
  <% end %>
  <%= render(partial: 'shared/navbar') %>
  <div class="wrapper">
    <%= yield %>
  </div>
  </body>
</html>

app/views/rates/index.html.erb
<div class="wrapper-rates">
  <div class="container">
    <p class="title">My exchange rates</p>
    <%= form_tag(rates_path, method: :post, class: 'form-inline') do %>
      <div class="form-group">
        <%= select_tag('rate[currency_from_id]', options_from_collection_for_select(Currency.all, :id, :description), class: 'form-control') %>
      </div>
      <div class="form-group">
        <%= select_tag('rate[currency_to_id]', options_from_collection_for_select(Currency.all, :id, :description), class: 'form-control') %>
      </div>
      <%= submit_tag 'Create rate', class: 'btn btn-primary' %>
    <% end %>
    <% if @rates.present? %>
    <table class="table">
      <thead>
      <tr>
        <th class="text-left">Currency From</th>
        <th class="text-left">Currency To</th>
        <th class="text-left">Amount</th>
        <th class="text-left">Remove</th>
      </tr>
      </thead>
      <tbody>
      <% @rates.each do |rate| %>
        <tr>
          <td class="text-left">
            <%= rate.currency_from.description %>
          </td>
          <td class="text-left">
            <%= rate.currency_to.description %>
          </td>
          <td class="text-left">
            <%= rate.amount %>
          </td>
          <td class="text-left">
            <%= link_to rate_path(rate.id), method: :delete do %>
              <span class="glyphicon glyphicon-remove"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class = 'navbar navbar-default'>
  <div class = 'container-fluid'>
    <div class = 'navbar-header'>
      <button type = 'button' class = 'navbar-toggle collapsed' data-toggle = 'collapse' data-target = '#bs-example-navbar-collapse-1' aria-expanded = 'false'>
        <span class = 'sr-only'>Toggle navigation</span>
        <span class = 'icon-bar'></span>
        <span class = 'icon-bar'></span>
        <span class = 'icon-bar'></span>
      </button>
      <%= link_to(root_path, class: 'navbar-brand') do %>
        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
      <% end %>
      <%= link_to("https://www.amdoren.com", class: 'navbar-brand') do %>
        Powered by Amdoren
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li> <%= link_to 'My exchange rates', rates_path %></li>
              <li role="separator" class="divider"></li>
              <li>  <%= link_to 'Log out',  destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li>  <%= link_to 'Log in',  new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>